export const MAX_FILE_SIZE_BYTES = 1_000_000; // 1MB per file
export const MAX_TOTAL_SIZE_BYTES = 100_000_000; // 100MB total
export const MAX_FILE_COUNT = 10_000;

export const GITHUB_API_BASE = 'https://api.github.com';

export const DEFAULT_IGNORE_PATTERNS = [
  'node_modules/',
  '.git/',
  'dist/',
  'build/',
  '.next/',
  '__pycache__/',
  '.tox/',
  'vendor/',
  '.bundle/',
  'target/',
  'coverage/',
  '.nyc_output/',
  '.cache/',
  '.turbo/',
  '.DS_Store',
  'thumbs.db',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.lock',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'Gemfile.lock',
  'Cargo.lock',
  'poetry.lock',
  'composer.lock',
];

export const BINARY_EXTENSIONS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.ico', '.svg', '.webp', '.avif',
  '.mp3', '.mp4', '.wav', '.ogg', '.webm', '.flac', '.aac',
  '.zip', '.tar', '.gz', '.bz2', '.7z', '.rar', '.xz',
  '.pdf', '.doc', '.docx', '.ppt', '.pptx', '.xls', '.xlsx',
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.exe', '.dll', '.so', '.dylib', '.o', '.a',
  '.pyc', '.pyo', '.class', '.jar', '.war',
  '.sqlite', '.db', '.sqlite3',
  '.DS_Store',
  '.lockb',
]);

export const README_PATTERNS = [
  /^readme(\.(md|txt|rst|adoc|org))?$/i,
];

export const MANIFEST_FILES = new Set([
  'package.json',
  'cargo.toml',
  'pyproject.toml',
  'go.mod',
  'requirements.txt',
  'gemfile',
  'build.gradle',
  'build.gradle.kts',
  'pom.xml',
  'composer.json',
  'mix.exs',
  'deno.json',
  'deno.jsonc',
  'bunfig.toml',
]);

export const LANGUAGE_MAP: Record<string, string> = {
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript',
  '.js': 'JavaScript',
  '.jsx': 'JavaScript',
  '.mjs': 'JavaScript',
  '.cjs': 'JavaScript',
  '.py': 'Python',
  '.rb': 'Ruby',
  '.go': 'Go',
  '.rs': 'Rust',
  '.java': 'Java',
  '.kt': 'Kotlin',
  '.kts': 'Kotlin',
  '.swift': 'Swift',
  '.cs': 'C#',
  '.c': 'C',
  '.cpp': 'C++',
  '.cc': 'C++',
  '.h': 'C',
  '.hpp': 'C++',
  '.php': 'PHP',
  '.scala': 'Scala',
  '.ex': 'Elixir',
  '.exs': 'Elixir',
  '.erl': 'Erlang',
  '.hs': 'Haskell',
  '.lua': 'Lua',
  '.r': 'R',
  '.dart': 'Dart',
  '.vue': 'Vue',
  '.svelte': 'Svelte',
  '.astro': 'Astro',
  '.html': 'HTML',
  '.css': 'CSS',
  '.scss': 'SCSS',
  '.sass': 'SASS',
  '.less': 'LESS',
  '.json': 'JSON',
  '.yaml': 'YAML',
  '.yml': 'YAML',
  '.toml': 'TOML',
  '.xml': 'XML',
  '.md': 'Markdown',
  '.mdx': 'MDX',
  '.sql': 'SQL',
  '.sh': 'Shell',
  '.bash': 'Shell',
  '.zsh': 'Shell',
  '.fish': 'Shell',
  '.ps1': 'PowerShell',
  '.tf': 'Terraform',
  '.proto': 'Protocol Buffers',
  '.graphql': 'GraphQL',
  '.gql': 'GraphQL',
  '.zig': 'Zig',
  '.nim': 'Nim',
  '.ml': 'OCaml',
  '.mli': 'OCaml',
  '.clj': 'Clojure',
  '.cljs': 'Clojure',
};
